# Identify directories.
input_dir: "clatr_data/input"
output_dir: "clatr_data/output"
output_label: "test Infoscopy refactor"
database_dir: "clatr_data/database"

# Control tabular and visual output.
cluster: false
aggregate: false
visualize: false
cohen_d_threshold: 0.8
max_feature_visuals: 5

# Designate tiers (units of analysis).
tiers:
  site:
    values:
    - AC
    - BU
    - TU
  test:
    values:
    - Pre
    - Post
    - Maint
  study_id:
    values: (AC|BU|TU)\d+
  narrative:
    values:
    - CATGrandpa
    - BrokenWindow
    - RefusedUmbrella
    - CatRescue
    - BirthdayScene

# Designate groupings for aggregation and comparison.
groupings:
  - tiers: 1,2
    aggregate: true
    compare: true
  - tiers: 1,2,3,4
    aggregate: true
    compare: false

all_comparison_combos: false
compare_with_clusters: false

all_aggregation_combos: false
aggregate_with_clusters: false

## CLATR-specific:
# Specify granularity.
document_level: true
sentence_level: false
paragraph_level: false
word_level: false

# Select analyses.
graphemes: true
lexicon: false
morphology: false
syntax: false
phonology: false
semantics: false
mechanics: false

ngrams: 5

dep_trees: false

# .cha files
exclude_speakers:
  - INV
